services:    
    cart-node:
      env_file: 
        - ../docker/environments/dev.env
      networks:
       - shared-swarm-net-dev
  
  
    cart-db:
      # ports:
      #    - 27018:27017
      networks:
       - shared-swarm-net-dev

    
    filebeat:
      networks:
         - shared-swarm-net-dev
