services:    
    cart-node:
      env_file: 
        - environments/${TARGETENV}.env
      expose: 
        - 9095
      networks:
       - mynetwork-prod
    

    cart-db:
      ports:
         - 27019:27017
      networks:
       - mynetwork-prod
      