services:    
    cart-node:
      env_file: 
        - environments/${TARGETENV}.env
      expose: 
        - 9095
      # volumes:
      #    - C:/Users/User/certificates/self-signed-custom-ca/rootCA.crt:/var/lib/certs/rootCA.crt
      #    - C:/Users/User/certificates/self-signed-custom-ca/cart.key:/var/lib/certs/cart.key
      #    - C:/Users/User/certificates/self-signed-custom-ca/cart.crt:/var/lib/certs/cart.crt
      networks:
       - mynetwork-prod
    

    cart-db:
      ports:
         - 27019:27017
      networks:
       - mynetwork-prod
      