services:    
    cart-node:
      env_file: 
        - environments/${TARGETENV}.env
      expose: 
        - 9091
      networks:
       - mynetwork-dev

              
    cart-db:
      ports:
         - 27018:27017
      networks:
       - mynetwork-dev

