apiVersion: v1
kind: Service
metadata:
 name: {{.Values.services.express.name}}-service-{{.Values.global.environment}}  #service name
spec:
 type: {{.Values.services.express.type}}  #type of service
 selector:
    app: {{.Values.services.express.name}}-deployment-{{.Values.global.environment}} #selecting the pods
 ports: 
   - port: {{.Values.services.express.port}}
     targetPort: {{.Values.app.express.port}} # this is the container port to which requests are forwarded to 
